apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  ports:
    - port: 80
  selector:
    app: nodeapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodeapp
        tier: frontend
    spec:
      containers:
      - image: dguer/nodeapp:${TAG}
        name: nodeapp
        ports:
        - containerPort: 80
          name: nodeapp