apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dguerfhwnnodeapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dguerfhwnnodeapp 
    spec:
      containers:
        - name: dguerfhwnnodeapp 
          image: containernodeapp.azurecr.io/dguerfhwnnodeapp
          ports:
          - containerPort: 80